modes:  
  # init:                           # (initial position - fully straight)
  #   info: [[0, 0], [0, 0]]
  stand:                          # switch_index = 0    (stand position - knees bent)
    info: [[0, 0], [0, 0]]
  walk:                           # switch_index = 1    (walk motion)
    index: 0
    swing_leg: 'left'
    info: [[1, 2, 3], [4, 5, 6]]
  turn:                           # switch_index = 2    (turn motion)
    dir:  'left'
    info: [[0, 0], [0, 0]]
  rise:                           # switch_index = 3    (rise motion)
    index: 0
    info: [[0, 0], [0, 0]]